//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be :
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.
//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#pragma once

#include "BaseProblem.h"


class Problem2 : public BaseProblem
{
public:
   Problem2();
   ~Problem2();

protected:
   virtual void Execute();
   virtual std::string ProblemName() { return "Problem2"; }
};